services:
  postgres:
    container_name: ledgerflow-postgres
    image: postgres:15
    command: postgres -c password_encryption=scram-sha-256
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ledgerflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./services/migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: ledgerflow-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    hostname: kafka
    container_name: ledgerflow-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # Dual listener config
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      # (Optional but recommended for single-broker if you ever use transactions/idempotent producer)
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server kafka:29092 --list > /dev/null 2>&1"]
      # test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list > /dev/null 2>&1"]
      interval: 5s
      timeout: 5s
      retries: 20

    restart: unless-stopped

  pgbouncer:
    container_name: ledgerflow-pgbouncer
    image: edoburu/pgbouncer
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: ledgerflow
      POOL_MODE: transaction
      MAX_CLIENT_CONN: 200
      DEFAULT_POOL_SIZE: 20
      AUTH_TYPE: scram-sha-256
    ports:
      - "6432:5432"
    restart: unless-stopped

  ledger:
    container_name: ledgerflow-ledger
    build:
      context: ./services/ledger-go
    ports:
      - "8081"
    environment:
      DATABASE_URL: postgres://postgres:postgres@pgbouncer:5432/ledgerflow?sslmode=disable
      KAFKA_BROKERS: kafka:29092
      KAFKA_TOPIC: ledger.transactions
    depends_on:
      pgbouncer:
        condition: service_started
      kafka:
        condition: service_healthy
    restart: unless-stopped

  read-model-builder:
    container_name: ledgerflow-read-model
    build:
      context: ./services/read-model-builder
    ports:
      - "9101:9101"
    environment:
      DATABASE_URL: postgres://postgres:postgres@pgbouncer:5432/ledgerflow?sslmode=disable
      KAFKA_BROKERS: kafka:29092
      KAFKA_TOPIC: ledger.transactions
      METRICS_ADDR: ":9101"
      REBUILD: "false"
    depends_on:
      pgbouncer:
        condition: service_started
      kafka:
        condition: service_healthy
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: ledgerflow-prometheus
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - ledger
      - read-model-builder
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: ledgerflow-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./infra/grafana/provisioning:/etc/grafana/provisioning
      - ./infra/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    restart: unless-stopped

  loki:
    image: grafana/loki:2.9.4
    container_name: ledgerflow-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./infra/loki/loki-config.yml:/etc/loki/local-config.yaml
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.9.4
    container_name: ledgerflow-promtail
    command: -config.file=/etc/promtail/promtail-config.yml
    volumes:
      - ./infra/promtail:/etc/promtail
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    depends_on:
      - loki
    restart: unless-stopped

  billing:
    container_name: ledgerflow-billing
    build:
      context: ./services/billing
    environment:
      PYTHONUNBUFFERED: "1"
      DATABASE_URL: postgres://postgres:postgres@pgbouncer:5432/ledgerflow?sslmode=disable
      KAFKA_BROKERS: kafka:29092
      KAFKA_CONSUME_TOPIC: ledger.transactions
      KAFKA_CONSUMER_GROUP: billing-service
      KAFKA_PRODUCE_TOPIC: billing.events
    depends_on:
      pgbouncer:
        condition: service_started
      kafka:
        condition: service_healthy
    restart: unless-stopped


volumes:
  postgres_data:
