version: '3.8'

services:
  postgres:
    container_name: ledgerflow-postgres
    image: postgres:15
    command: postgres -c password_encryption=scram-sha-256
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ledgerflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: unless-stopped

  pgbouncer:
    container_name: ledgerflow-pgbouncer
    image: edoburu/pgbouncer
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: ledgerflow
      POOL_MODE: transaction
      MAX_CLIENT_CONN: 200
      DEFAULT_POOL_SIZE: 20
      AUTH_TYPE: scram-sha-256
    ports:
      - "6432:5432"
    restart: unless-stopped

  ledger:
    container_name: ledgerflow-ledger
    build:
      context: ./services/ledger-go
    ports:
      - "8080:8081"
    environment:
      DATABASE_URL: postgres://postgres:postgres@pgbouncer:5432/ledgerflow?sslmode=disable
      KAFKA_BROKERS: kafka:29092
      KAFKA_TOPIC: ledger.transactions
    depends_on:
      - pgbouncer
      - kafka
    restart: unless-stopped

  read-model-builder:
    container_name: ledgerflow-read-model
    build:
      context: ./services/read-model-builder
    depends_on:
      - pgbouncer
      - kafka
    restart: unless-stopped
    ports:
      - "9101:9101"
    environment:
      DATABASE_URL: postgres://postgres:postgres@pgbouncer:5432/ledgerflow?sslmode=disable
      KAFKA_BROKERS: kafka:29092
      KAFKA_TOPIC: ledger.transactions
      METRICS_ADDR: :9101


volumes:
  postgres_data:
