global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "ledger-go"
    static_configs:
      - targets: ["ledger:8081"]

  - job_name: "read-model"
    static_configs:
      - targets: ["read-model-builder:9101"]
